language: node_js
node_js: stable

script:
  - echo hello

deploy:
  provider: pages
  skip-cleanup: true
  githup-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./class4/test-app/build
  on:
    branch: master